//! §6.1/§7.3 tensor order, physical scaling, orientation, invalid voxels and raw-frame preservation.
//! References: nibabel + numpy.linalg.eigh, regenerated by scripts/refvalues/tensor_refvalues.py.
//! Real data: export TETRAVOX_TESTDATA=/path/to/sub-ernie. Pixel evidence lives in tensor.spec.ts.
use serde_json::Value;
use std::path::{Path, PathBuf};
use tvx_core::NoProgress;
use tvx_nifti::{
    read_nifti,
    tensor::{tensor_payload, TensorBasis, TensorOrder},
    Volume,
};

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}
fn load(path: &Path) -> Volume {
    read_nifti(std::fs::read(path).unwrap(), &mut NoProgress).unwrap()
}
fn verify(v: &Volume, reference: &Value, stride: usize) {
    let order = if reference["order"] == "nifti" {
        TensorOrder::Nifti
    } else {
        TensorOrder::Fsl
    };
    let payload = tensor_payload(v, order, TensorBasis::Fsl, stride, 4096).unwrap();
    let grid = [payload.dims[0], payload.dims[1], payload.dims[2] / 8];
    let n = grid.iter().product::<usize>();
    let spots = reference["spots"].as_array().unwrap();
    assert!(!spots.is_empty());
    let mut checked = 0;
    for spot in spots {
        let ijk: Vec<usize> = spot["voxel"]
            .as_array()
            .unwrap()
            .iter()
            .map(|n| n.as_u64().unwrap() as usize)
            .collect();
        if ijk.iter().any(|i| i % stride != 0) {
            continue;
        }
        checked += 1;
        let i = ((ijk[2] / stride) * grid[1] + ijk[1] / stride) * grid[0] + ijk[0] / stride;
        let actual: Vec<f64> = (0..8).map(|k| payload.data[i + k * n] as f64).collect();
        if !spot["valid"].as_bool().unwrap() {
            assert!(actual.iter().all(|v| *v == 0.));
            continue;
        }
        for (k, value) in actual.iter().take(6).enumerate() {
            let expected = spot["metric"][k].as_f64().unwrap();
            // R32F payload: relative tolerance covers one rounding plus the eigensolver's tail.
            assert!(
                (value - expected).abs() < 2e-5 * expected.abs().max(1.),
                "metric {k}: {value} vs {expected}"
            );
        }
        assert!((actual[7] - spot["fa"].as_f64().unwrap()).abs() < 1e-6);
        let rgb: Vec<u32> = spot["rgb"]
            .as_array()
            .unwrap()
            .iter()
            .map(|n| n.as_u64().unwrap() as u32)
            .collect();
        assert_eq!(actual[6] as u32, rgb[0] + 256 * rgb[1] + 65536 * rgb[2]);
    }
    assert!(checked > 0);
}

#[test]
fn tensor_numpy_reference_and_original_frames() {
    let refs: Value = serde_json::from_str(
        &std::fs::read_to_string(repo().join("testdata/tensors.json")).unwrap(),
    )
    .unwrap();
    for reference in refs.as_array().unwrap() {
        let v = load(
            &repo()
                .join("testdata")
                .join(reference["file"].as_str().unwrap()),
        );
        assert_eq!(v.nvols, 6);
        let before = v.stats(0);
        verify(&v, reference, 1);
        verify(&v, reference, 2);
        assert_eq!(v.stats(0).min, before.min);
        assert_eq!(v.stats(0).max, before.max);
        assert_eq!(v.stats(0).mean, before.mean);
    }
}

#[test]
fn rejects_scalar_wrong_stride_and_oversize_grid() {
    let v = load(&repo().join("testdata/tensor_fsl.nii.gz"));
    assert!(tensor_payload(&v, TensorOrder::Fsl, TensorBasis::Fsl, 0, 2048).is_err());
    assert!(tensor_payload(&v, TensorOrder::Fsl, TensorBasis::Fsl, 1, 8).is_err());
    let mut scalar = v.clone();
    scalar.nvols = 1;
    assert!(tensor_payload(&scalar, TensorOrder::Fsl, TensorBasis::Fsl, 2, 2048).is_err());
    let mut sheared = v.clone();
    sheared.affine[0][1] = 0.5;
    assert!(tensor_payload(&sheared, TensorOrder::Fsl, TensorBasis::Voxel, 2, 2048).is_err());
    assert!(tensor_payload(&sheared, TensorOrder::Fsl, TensorBasis::World, 2, 2048).is_ok());
}

#[test]
fn ernie_tensor_and_t1_numpy_reference() {
    let Some(root) = std::env::var_os("TETRAVOX_TESTDATA").map(PathBuf::from) else {
        eprintln!("skipping: TETRAVOX_TESTDATA is unset");
        return;
    };
    let tensor = root.join("m2m_ernie/DTI_coregT1_tensor.nii.gz");
    let t1 = root.join("m2m_ernie/T1.nii.gz");
    if !tensor.is_file() || !t1.is_file() {
        eprintln!("skipping: ernie tensor/T1 files are missing");
        return;
    }
    let reference: Value = serde_json::from_str(
        &std::fs::read_to_string(repo().join("scripts/refvalues/tensor_refvalues.json")).unwrap(),
    )
    .unwrap();
    let v = load(&tensor);
    verify(&v, &reference, 2);
    let anatomy = load(&t1);
    assert_eq!(v.dims, anatomy.dims);
    assert_eq!(anatomy.nvols, 1);
    assert_eq!(anatomy.stats(0).max, 65535.);
    for i in 0..4 {
        for j in 0..4 {
            assert!((v.affine[i][j] - reference["affine"][i][j].as_f64().unwrap()).abs() < 1e-5);
            assert!((v.affine[i][j] - anatomy.affine[i][j]).abs() < 1e-5);
        }
    }
}

#[test]
fn nonfinite_components_never_produce_glyphs() {
    let mut v = load(&repo().join("testdata/tensor_fsl.nii.gz"));
    if let tvx_nifti::VolumeData::F32(data) = &mut v.data {
        data[0] = f32::NAN;
        data[1] = f32::INFINITY;
    } else {
        panic!("fixture must be float32");
    }
    let payload = tensor_payload(&v, TensorOrder::Fsl, TensorBasis::Fsl, 1, 2048).unwrap();
    let n = v.dims.iter().product::<usize>();
    for k in 0..8 {
        assert_eq!(payload.data[k * n], 0.);
        assert_eq!(payload.data[k * n + 1], 0.);
    }
    assert!(payload.data.iter().all(|v| v.is_finite()));
}
