/**
 * The §7.4 mesh program.
 *
 * Phase 1 shipped the **minimum**: indexed tag surfaces with the tag colour as a uniform, headlight
 * Blinn-Phong, two-sided lighting, `faceMode`. Phase 2's "§7.4 complete" extends this file and only
 * this file — the clip-distance variants N ∈ 0..6 land beside these defines, and `ProgramVariants`
 * (`gl/program.ts`) already keys on them because §7.1 says a blanket `[6]` costs 20 % of the varying
 * budget on every mesh program.
 *
 * **The `TVX_COLOR_SOURCE = 0`, no-edges, no-flat, no-threshold variant is Phase 1's shader
 * verbatim.** The `#if`s fold away to exactly the Phase-1 source, so the two Phase-1 gate goldens
 * that contain a mesh do not move.
 *
 * ## Defines
 *
 * | define | meaning |
 * |---|---|
 * | `TVX_COLOR_SOURCE` | 0 = uniform colour (`colorMode` `'tag'` / `'solid'`) · 1 = node field · 2 = element field · 3 = label · 4 = per-element cap tag |
 * | `TVX_EDGES` | barycentric edges; implies the de-indexed variant's `corner` attribute |
 * | `TVX_EDGE_MASK` | the per-triangle 3-bit mask exists; 0 = every edge is real, folded to a constant |
 * | `TVX_FLAT_SHADING` | face normal from screen-space derivatives instead of the interpolated one |
 * | `TVX_THRESHOLD` | 0 = none · 1 = `mode:'hide'` on `v` · 2 = `mode:'hide'` on `abs(v)` (`symmetric`) |
 * | `TVX_EMPHASIS` | selected-label edge emphasis (R5); `TVX_COLOR_SOURCE == 3` only |
 * | `TVX_CLIP_PLANES` | N ∈ 0..6 active clip planes (§7.4). N = 0 emits no `#extension` and no redeclaration |
 * | `TVX_CLIP_DISCARD` | 1 = the `vec4`-uniform + `discard` fallback instead of `gl_ClipDistance` |
 * | `TVX_CAP` | this draw is a `plane_cut` cap: attributes and normal come from the cut, not the surface |
 * | `TVX_CAP_MIX` | a field-coloured cap whose layer mixes paints (`tagStyle[tag].colorMode`): reads the tet-tag palette, paints 'color' tags flat, hides alpha-0 ones |
 *
 * ## Clipping — two paths, one geometry, pixel-identical (§7.4, §11)
 *
 * Sign convention is byte-for-byte §6.0's `Plane`: `dot(plane.normal, worldPos) + plane.offset`, keep
 * `>= 0`. **No negation, no separate GPU convention**, and the two paths evaluate the *same*
 * expression on the *same* world position:
 *
 * * **Hardware** (`TVX_CLIP_DISCARD 0`): `#extension GL_ANGLE_clip_cull_distance : require` — `require`,
 *   not `enable`, so a driver lacking it fails at **compile** time and trips the fallback rather than
 *   rendering unclipped — plus `out highp float gl_ClipDistance[N]` and N **unrolled constant-index**
 *   assignments. N is a variant key because on ANGLE/Metal each clip distance costs a full varying
 *   vector out of `MAX_VARYING_VECTORS = 30`, so a blanket `[6]` would tax every mesh program forever.
 * * **Fallback** (`TVX_CLIP_DISCARD 1`): the same `vec4` plane uniforms, evaluated per fragment against
 *   the already-interpolated `vWorld`. `dot` is affine in position, so the interpolated clip distance
 *   and the recomputed one are the same number.
 *
 * **The cap rule** (§7.4, "the one that breaks the product"): when drawing the cap generated by plane
 * *i*, plane *i* must not clip it — cap vertices lie exactly **on** that plane, and `gl_ClipDistance ==
 * −1e-7` deletes the primitive entirely `[M2Max]`. The hardware path disables `CLIP_DISTANCE(i)` for
 * that draw (`GlState.clipDistances(count, except)`); the fallback path skips index `uClipSkip`. The
 * two are the same rule, expressed once per path, and nothing in this file re-derives it.
 *
 * ## Caps (`TVX_CAP`)
 *
 * A cap is `plane_cut`'s exact per-element polygon soup drawn **with the layer's own material** (§7.4),
 * so it is a variant of this program rather than a program of its own — one LUT, one threshold, one
 * edge mechanism, one lighting model, no second place for them to drift.
 *
 * What differs from a surface draw, and only this:
 * * **Normals are a uniform.** "Cap normals are the (negated) clip-plane normal, generated engine-side;
 *   `Cut` carries no normal buffer" (§7.4). There is no `aNormal` attribute on a cap VAO.
 * * **The corner ordinal is `gl_VertexID % 3`.** A cut is de-indexed by construction and drawn with
 *   `drawArrays`, so no `corner` attribute is needed or shipped.
 * * **A node field is `mix(f[n0], f[n1], t)`** from the `interpNodes` / `interpT` attributes §6.5.1
 *   puts on every cut vertex — §7.4's "changing the displayed field costs zero re-cut", done in the
 *   vertex shader exactly as the contract describes.
 * * **An element field and the pick id come from the per-vertex `ownerTet`** rather than a texture
 *   fetch at `gl_VertexID / 3`: §7.2.3 says cut caps "are already de-indexed and carry `ownerElm`".
 * * **`TVX_COLOR_SOURCE 4`** is the per-element **tet tag**, as a dense index into the same
 *   `N x 2 RGBA8` palette the label path uses — so `tagStyle` recolour / hide on a cap is one palette
 *   re-upload and no re-cut (R5).
 *
 * ## Where each colour comes from, and why
 *
 * * **Node field (1).** §7.4's indexed variant carries `nodeIndex` — "vertex → INTERNAL 0-based node
 *   index, which is what the §7.4 node-field texture is indexed by". One `texelFetch` in the vertex
 *   shader and one interpolated `float` varying: a node field is *smooth* by construction.
 * * **Element field (2).** §7.4's de-indexed variant, "the per-face scalar from
 *   `texelFetch(elmFieldTex, ivec2(...), 0)` at `gl_VertexID / 3`". The triangle's element comes from
 *   the same `ownerElm` R32UI table the pick pass reads, so no per-vertex id attribute is built (§5
 *   rule 7). All three vertices of a triangle fetch the same value, so the varying interpolates a
 *   constant — the field is *flat* with no `flat` qualifier and no dependence on ES's last-vertex
 *   provoking rule, which §7.4 rejects as a shortcut.
 * * **Label (3).** A `.annot` / `.label.gii` label is a **node** quantity, and §6.2 remaps it to a
 *   dense `0..N−1` index at parse time, so the value in the node table *is* the palette index. The
 *   palette is an `N×2 RGBA8` texture: row 0 is the label's colour with its visibility folded into
 *   alpha (recolour / hide / solo are all a palette re-upload — R5), row 1's red channel is whether
 *   the label is selected. Both are read in the vertex shader; inside a label — every triangle whose
 *   three corners agree, which is all but the seam — the interpolant is exactly the palette colour,
 *   so §11's 0..255 round trip holds on the pixel.
 *
 * ## Edges
 *
 * §7.4's mechanism verbatim: a 3-bit `edgeMask`, `d = bary / fwidth(bary)`, `d[i] = 1e9` for cleared
 * bits so a suppressed edge never contributes to the `min` and slivers do not flood, shaded
 * `1 − smoothstep(w − 0.5, w + 0.5, min(d))`. The corner ordinal is the 1-byte `corner` attribute
 * expanded to a `vec3` here — never three floats per vertex.
 *
 * The mask itself is a **per-triangle `R8UI` texture** read at `gl_VertexID / 3`, not the per-vertex
 * attribute §7.4 names: `SurfacePayload.edgeMask` is one byte per *triangle*, so binding it as a
 * per-vertex attribute would mean expanding it 3× on the UI thread, and §5 rule 7 puts every
 * vertex-buffer expansion in the worker. §7.4's "when a whole draw is unmasked ... the common case
 * costs zero memory" is served one better by `TVX_EDGE_MASK 0`, which folds the mask to a compile-
 * time `vec3(1)` — no attribute slot, no buffer, no fetch. See docs/DECISIONS.md.
 *
 * The **selected-label emphasis** (R5) reuses the same idea one dimension up: the per-vertex
 * "selected" indicator interpolates 0…1 across a seam, and `abs(s − 0.5) / fwidth(s)` is the distance
 * in **pixels** from the selection boundary, so the band keeps its width at any zoom.
 */

import {
  CLIP_DEFINES,
  CLIP_DISCARD,
  CLIP_EXTENSION,
  CLIP_UNIFORMS,
  CLIP_WRITE,
  PRECISION_FLOAT,
  PRECISION_INT,
  PRECISION_SAMPLER2D,
  PRECISION_USAMPLER2D,
  VERSION,
} from './chunks/caps';

/** `TVX_COLOR_SOURCE` values, so the pass and the shader cannot drift apart. */
export const MESH_COLOR_SOURCE = {
  uniform: 0,
  nodeField: 1,
  elmField: 2,
  label: 3,
  /** Per-element **tet** tag on a cap, as a dense index into the tag palette (`TVX_CAP` only). */
  capTag: 4,
} as const;

/** `TVX_THRESHOLD` values (§4.2: `mode:'clamp'` needs no discard — the CPU bake already clamps). */
export const MESH_THRESHOLD = {
  none: 0,
  hide: 1,
  hideSymmetric: 2,
} as const;

export const MESH_VS = `${VERSION}
#ifndef TVX_CAP_MIX
#define TVX_CAP_MIX 0
#endif
#ifndef TVX_COLOR_SOURCE
#define TVX_COLOR_SOURCE 0
#endif
#ifndef TVX_EDGES
#define TVX_EDGES 0
#endif
#ifndef TVX_EDGE_MASK
#define TVX_EDGE_MASK 0
#endif
#ifndef TVX_EMPHASIS
#define TVX_EMPHASIS 0
#endif
#ifndef TVX_CAP
#define TVX_CAP 0
#endif
${CLIP_DEFINES}
${CLIP_EXTENSION}
${PRECISION_FLOAT}
${PRECISION_INT}
${PRECISION_SAMPLER2D}
${PRECISION_USAMPLER2D}
layout(location = 0) in vec3 aPos;
#if TVX_CAP == 0
layout(location = 1) in vec3 aNormal;
#if TVX_EDGES
layout(location = 2) in uint aCorner;
#endif
#if TVX_COLOR_SOURCE == 1 || TVX_COLOR_SOURCE == 3
layout(location = 4) in uint aNodeIndex;
#endif
#else
// §6.5.1's cut attributes. A cap carries no normal (the plane's is a uniform) and no corner (a cut
// is de-indexed, so the ordinal is gl_VertexID % 3).
#if TVX_COLOR_SOURCE == 1
layout(location = 5) in uvec2 aInterpNodes;
layout(location = 6) in float aInterpT;
#endif
#if TVX_COLOR_SOURCE == 4 || TVX_CAP_MIX
layout(location = 7) in int aCapTag;      // dense index into the tag palette
#endif
#if TVX_COLOR_SOURCE == 2
layout(location = 8) in uint aOwnerTet;   // Gmsh element number (§6.2), 1-based
#endif
#if TVX_EDGES && TVX_EDGE_MASK
layout(location = 9) in uint aCapEdgeMask;
#endif
uniform vec3 uCapNormal;          // the (negated) clip-plane normal, generated engine-side (§7.4)
#endif
uniform mat4 uViewProj;
uniform mat4 uModel;
${CLIP_UNIFORMS}
#if TVX_COLOR_SOURCE >= 1 && TVX_COLOR_SOURCE <= 3
uniform sampler2D uFieldTex;      // R32F: one texel per node (1, 3) or per element (2)
uniform int uFieldWidth;
#endif
#if TVX_COLOR_SOURCE == 2 && TVX_CAP == 0
uniform usampler2D uOwnerTex;     // the pick pass's ownerElm table, reused (§7.2.3)
uniform int uOwnerWidth;
#endif
#if TVX_EDGES && TVX_EDGE_MASK && TVX_CAP == 0
uniform usampler2D uEdgeMaskTex;  // R8UI, §7.4's 3-bit mask, one texel per triangle
uniform int uEdgeMaskWidth;
#endif
#if TVX_COLOR_SOURCE == 3 || TVX_COLOR_SOURCE == 4 || TVX_CAP_MIX
uniform sampler2D uPalette;       // N x 2 RGBA8: row 0 colour+visibility, row 1 (r selection, g flat paint)
uniform int uPaletteSize;
#endif
#if TVX_CLIP_PLANES > 0 && TVX_CLIP_DISCARD == 0
out highp float gl_ClipDistance[TVX_CLIP_PLANES];
#endif
out vec3 vWorld;
out vec3 vNormal;
#if TVX_COLOR_SOURCE == 1 || TVX_COLOR_SOURCE == 2
out float vScalar;
#endif
#if TVX_COLOR_SOURCE == 3 || TVX_COLOR_SOURCE == 4
out vec4 vLabelColor;
#if TVX_EMPHASIS
out float vLabelSelected;
#endif
#endif
#if TVX_CAP_MIX
flat out vec4 vCapFlatColor;      // the tet tag's own colour + visibility
flat out float vCapFlat;          // 1 = this tag paints flat, not by the field (tagStyle.colorMode)
#endif
#if TVX_EDGES
out vec3 vBary;
#if TVX_EDGE_MASK
out vec3 vEdgeOn;
#endif
#endif
void main() {
  vec4 w = uModel * vec4(aPos, 1.0);
  vWorld = w.xyz;
#if TVX_CAP
  // §7.4: "Cap normals are the (negated) clip-plane normal, generated engine-side; Cut carries no
  // normal buffer." A cap is planar, so one uniform is exact for every fragment of it.
  vNormal = mat3(uModel) * uCapNormal;
#else
  // The model transform is the user-editable MeshDataset.transform, which is identity on load and a
  // rigid/affine edit thereafter; the normal matrix is its inverse-transpose upper 3x3. For the
  // identity case this is exactly aNormal.
  vNormal = mat3(uModel) * aNormal;
#endif
#if TVX_COLOR_SOURCE == 1
#if TVX_CAP
  // §7.4's cap rule for a node field: the vertex shader does texelFetch + mix from interpNodes and
  // interpT, "so changing the displayed field costs zero re-cut".
  int n0 = int(aInterpNodes.x);
  int n1 = int(aInterpNodes.y);
  float f0 = texelFetch(uFieldTex, ivec2(n0 % uFieldWidth, n0 / uFieldWidth), 0).r;
  float f1 = texelFetch(uFieldTex, ivec2(n1 % uFieldWidth, n1 / uFieldWidth), 0).r;
  vScalar = mix(f0, f1, aInterpT);
#else
  int nodeRow = int(aNodeIndex);
  vScalar = texelFetch(uFieldTex, ivec2(nodeRow % uFieldWidth, nodeRow / uFieldWidth), 0).r;
#endif
#elif TVX_COLOR_SOURCE == 2
#if TVX_CAP
  // §7.2.3: "Cut caps and flat-shaded field geometry are already de-indexed and carry ownerElm."
  int elmRow = max(int(aOwnerTet) - 1, 0);
#else
  int tri = gl_VertexID / 3;
  uint owner = texelFetch(uOwnerTex, ivec2(tri % uOwnerWidth, tri / uOwnerWidth), 0).r;
  // §6.2's identity numbering: a Gmsh element number is its 0-based row plus one.
  int elmRow = max(int(owner) - 1, 0);
#endif
  vScalar = texelFetch(uFieldTex, ivec2(elmRow % uFieldWidth, elmRow / uFieldWidth), 0).r;
#elif TVX_COLOR_SOURCE == 3
  int nodeRow = int(aNodeIndex);
  // §6.2 remaps a packed .annot / .label.gii id to a dense 0..N-1 index at parse time, so the node
  // value IS the palette index; the +0.5 round-trip is exact for the integers that remap produces.
  float raw = texelFetch(uFieldTex, ivec2(nodeRow % uFieldWidth, nodeRow / uFieldWidth), 0).r;
  int k = clamp(int(floor(raw + 0.5)), 0, uPaletteSize - 1);
  vLabelColor = texelFetch(uPalette, ivec2(k, 0), 0);
#if TVX_EMPHASIS
  vLabelSelected = texelFetch(uPalette, ivec2(k, 1), 0).r;
#endif
#elif TVX_COLOR_SOURCE == 4
  // The cap's per-element tet tag, already dense: one texel of the same palette the label path
  // reads, so a tagStyle recolour or hide is an 8N-byte re-upload and no re-cut (R5).
  int k = clamp(aCapTag, 0, uPaletteSize - 1);
  vLabelColor = texelFetch(uPalette, ivec2(k, 0), 0);
#if TVX_EMPHASIS
  vLabelSelected = texelFetch(uPalette, ivec2(k, 1), 0).r;
#endif
#endif
#if TVX_CAP_MIX
  {
    int mk = clamp(aCapTag, 0, uPaletteSize - 1);
    vCapFlatColor = texelFetch(uPalette, ivec2(mk, 0), 0);
    vCapFlat = texelFetch(uPalette, ivec2(mk, 1), 0).g;
  }
#endif
#if TVX_EDGES
#if TVX_CAP
  int corner = gl_VertexID % 3;
  vBary = vec3(corner == 0, corner == 1, corner == 2);
#if TVX_EDGE_MASK
  vEdgeOn = vec3((aCapEdgeMask & 1u) != 0u, (aCapEdgeMask & 2u) != 0u, (aCapEdgeMask & 4u) != 0u);
#endif
#else
  vBary = vec3(aCorner == 0u, aCorner == 1u, aCorner == 2u);
#if TVX_EDGE_MASK
  int edgeTri = gl_VertexID / 3;
  uint m = texelFetch(uEdgeMaskTex,
                      ivec2(edgeTri % uEdgeMaskWidth, edgeTri / uEdgeMaskWidth), 0).r;
  // All three vertices of a triangle read the same texel, so this varying interpolates a constant.
  vEdgeOn = vec3((m & 1u) != 0u, (m & 2u) != 0u, (m & 4u) != 0u);
#endif
#endif
#endif
${CLIP_WRITE}
  gl_Position = uViewProj * w;
}`;

export const MESH_FS = `${VERSION}
#ifndef TVX_COLOR_SOURCE
#define TVX_COLOR_SOURCE 0
#endif
#ifndef TVX_EDGES
#define TVX_EDGES 0
#endif
#ifndef TVX_EDGE_MASK
#define TVX_EDGE_MASK 0
#endif
#ifndef TVX_FLAT_SHADING
#define TVX_FLAT_SHADING 0
#endif
#ifndef TVX_THRESHOLD
#define TVX_THRESHOLD 0
#endif
#ifndef TVX_EMPHASIS
#define TVX_EMPHASIS 0
#endif
#ifndef TVX_CAP_MIX
#define TVX_CAP_MIX 0
#endif
${CLIP_DEFINES}
${PRECISION_FLOAT}
${PRECISION_INT}
${PRECISION_SAMPLER2D}
in vec3 vWorld;
in vec3 vNormal;
#if TVX_CLIP_DISCARD == 1
${CLIP_UNIFORMS}
#if TVX_CLIP_PLANES > 0
uniform int uClipSkip;            // §7.4's cap rule: the plane whose own cap this draw is, or -1
#endif
#endif
#if TVX_COLOR_SOURCE == 1 || TVX_COLOR_SOURCE == 2
in float vScalar;
uniform sampler2D uLut;
uniform float uLutLo;
uniform float uLutHi;
#endif
#if TVX_COLOR_SOURCE == 3 || TVX_COLOR_SOURCE == 4
in vec4 vLabelColor;
#if TVX_EMPHASIS
in float vLabelSelected;
#endif
#endif
#if TVX_CAP_MIX
flat in vec4 vCapFlatColor;
flat in float vCapFlat;
#endif
#if TVX_THRESHOLD
uniform float uThreshLo;
uniform float uThreshHi;
uniform float uThreshSoft;
#endif
#if TVX_EDGES
in vec3 vBary;
#if TVX_EDGE_MASK
in vec3 vEdgeOn;
#endif
#endif
#if TVX_EDGES || TVX_EMPHASIS
uniform vec4 uEdgeColor;
uniform float uEdgeWidthPx;
#endif
uniform vec3 uEye;
uniform vec4 uColor;
uniform float uAmbient;
uniform float uOpacity;
out vec4 fragColor;
void main() {
${CLIP_DISCARD}
#if TVX_FLAT_SHADING
  // §4.4's flatShading. The face normal from screen-space derivatives of the world position needs no
  // second geometry variant and is exact for a planar triangle.
  vec3 n = normalize(cross(dFdx(vWorld), dFdy(vWorld)));
#else
  vec3 n = normalize(vNormal);
#endif
  vec3 v = normalize(uEye - vWorld);
  // Two-sided lighting (§7.4): an interface triangle's stored winding is arbitrary, and a surface
  // lit from behind would read as a hole.
  if (dot(n, v) < 0.0) n = -n;
  // Headlight: the light direction IS the view direction, so there is no light-position uniform.
  float diff = max(dot(n, v), 0.0);
  vec3 h = v;                       // halfway vector of a headlight is the view vector
  float spec = pow(max(dot(n, h), 0.0), 32.0) * 0.25;
#if TVX_COLOR_SOURCE == 0
  vec4 base = uColor;
#elif TVX_COLOR_SOURCE == 1 || TVX_COLOR_SOURCE == 2
  float lutT = (vScalar - uLutLo) / (uLutHi - uLutLo);
  vec4 base = texture(uLut, vec2(clamp(lutT, 0.0, 1.0), 0.5));
#else
  vec4 base = vLabelColor;
#endif
#if TVX_CAP_MIX
  // A hidden tet tag has palette alpha 0 and contributes nothing; a 'color'-painted one takes its
  // flat colour and skips the field threshold, exactly as its surface sub-draw does.
  if (vCapFlatColor.a <= 0.0) discard;
  bool capFlat = vCapFlat > 0.5;
  if (capFlat) base = vec4(vCapFlatColor.rgb, 1.0);
#endif
  float alpha = base.a * uOpacity;
#if TVX_THRESHOLD
#if TVX_CAP_MIX
  if (!capFlat) {
#endif
#if TVX_THRESHOLD == 2
  float tv = abs(vScalar);          // §4.2: a symmetric threshold compares |v|
#else
  float tv = vScalar;
#endif
  // §4.2 verbatim: softEdge is "the width of the alpha ramp as a fraction of hi - lo; 0 = hard
  // discard". The CPU passes that width already multiplied out and floored just above zero, so the
  // degenerate smoothstep(e, e, x) never appears.
  alpha *= smoothstep(uThreshLo, uThreshLo + uThreshSoft, tv);
  alpha *= 1.0 - smoothstep(uThreshHi - uThreshSoft, uThreshHi, tv);
#if TVX_CAP_MIX
  }
#endif
#endif
  vec3 rgb = base.rgb * (uAmbient + (1.0 - uAmbient) * diff) + vec3(spec);
#if TVX_EDGES
#if TVX_EDGE_MASK
  vec3 edgeOn = vEdgeOn;
#else
  // §7.4's "when a whole draw is unmasked" case, one better than the constant attribute it suggests:
  // a compile-time constant costs no attribute slot, no buffer and no fetch.
  vec3 edgeOn = vec3(1.0);
#endif
  // §7.4: d = bary / fwidth(bary), with a cleared mask bit pushed out of the min entirely.
  //
  // The select is the bvec3 overload of mix, and that is not a style choice. The float form
  // mix(x, y, a) is specified as x + a*(y - x), and with the 1e9 sentinel as x that evaluates
  // 1e9 + 1.0*(d - 1e9): in f32, d - 1e9 rounds to exactly -1e9 for every d a barycentric distance
  // can produce, so the sum is 0 and every KEPT edge reported distance zero -- which paints the
  // whole triangle in the edge colour. Measured on the cap of the 3x3x3 fixture [SwS]. The bvec3
  // overload is a genuine component select and does no arithmetic at all.
  vec3 dist = vBary / max(fwidth(vBary), vec3(1e-9));
  vec3 d = mix(vec3(1e9), dist, greaterThan(edgeOn, vec3(0.5)));
  float edge = 1.0 - smoothstep(uEdgeWidthPx - 0.5, uEdgeWidthPx + 0.5, min(min(d.x, d.y), d.z));
  rgb = mix(rgb, uEdgeColor.rgb, edge * uEdgeColor.a);
#endif
#if TVX_EMPHASIS && (TVX_COLOR_SOURCE == 3 || TVX_COLOR_SOURCE == 4)
  // The selected label's boundary, in screen space: abs(s - 0.5) / fwidth(s) is the distance in
  // pixels from the s = 0.5 iso-line, so the band keeps its width at any zoom (R5's outline
  // emphasis). Inside a label fwidth(s) is 0 and the band never appears.
  float sd = abs(vLabelSelected - 0.5) / max(fwidth(vLabelSelected), 1e-9);
  float emph = 1.0 - smoothstep(uEdgeWidthPx - 0.5, uEdgeWidthPx + 0.5, sd);
  rgb = mix(rgb, uEdgeColor.rgb, emph * uEdgeColor.a);
  alpha = max(alpha, emph * uEdgeColor.a);
#endif
  if (alpha <= 0.0) discard;
  fragColor = vec4(rgb, alpha);
}`;
