import { defineConfig } from 'vitepress';

/**
 * The Tetravox documentation site.
 *
 * `base` is read from an env var so the same build serves both localhost
 * (`/`) and GitHub Pages under a project path (`/tetravox/`) — set
 * TETRAVOX_DOCS_BASE=/tetravox/ in the Pages workflow and leave it unset
 * locally.
 */
const base = process.env.TETRAVOX_DOCS_BASE ?? '/';

export default defineConfig({
  title: 'Tetravox',
  description:
    'A desktop viewer for voxel volumes (NIfTI) and finite-element / surface meshes, with a linked 3D view and orthogonal slices.',
  base,
  lang: 'en-US',
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: false,

  // website/src/ is generated by scripts/sync.mjs and scripts/gallery.mjs
  // (see those scripts) — it holds the pages pulled straight from docs/*.md.
  // `rewrites` drops the src/ segment from the URL so a generated page and a
  // hand-written one (index.md, install.md, get-started.md, showcase.md, developers/building.md) sit at the same
  // URL depth — visitors never see the source/generated split.
  srcDir: '.',
  rewrites: {
    'src/guide/:page.md': 'guide/:page.md',
    'src/automation.md': 'automation.md',
    'src/gallery.md': 'gallery.md',
    'src/developers/architecture.md': 'developers/architecture.md',
    'src/developers/decisions.md': 'developers/decisions.md',
    'src/developers/testing.md': 'developers/testing.md',
    'src/developers/benchmarks.md': 'developers/benchmarks.md',
    'src/developers/roadmap.md': 'developers/roadmap.md',
    'src/developers/contributing.md': 'developers/contributing.md',
    'src/developers/releasing.md': 'developers/releasing.md',
  },

  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}favicon.svg` }],
    // PNG fallback for the browsers that still ignore an SVG favicon, and the
    // size iOS reaches for when the site is added to a home screen.
    ['link', { rel: 'icon', type: 'image/png', sizes: '180x180', href: `${base}favicon.png` }],
    ['link', { rel: 'apple-touch-icon', href: `${base}favicon.png` }],
    ['meta', { name: 'theme-color', content: '#1b1f26' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'Tetravox — voxel + mesh viewer' }],
    [
      'meta',
      {
        property: 'og:description',
        content:
          'A desktop viewer for voxel volumes and finite-element / surface meshes, one linked 3D view beside orthogonal slices.',
      },
    ],
  ],

  markdown: {
    theme: { light: 'github-light', dark: 'github-dark' },
    lineNumbers: false,
  },

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'Tetravox',
    outline: { level: [2, 3], label: 'On this page' },

    nav: [],

    sidebar: [
      {
        text: 'Guide',
        collapsed: false,
        items: [
          { text: 'Home', link: '/' },
          { text: 'Install', link: '/install' },
          { text: 'Get started', link: '/get-started' },
          {
            text: 'The wiki',
            collapsed: false,
            items: [
              { text: 'Opening data & formats', link: '/guide/opening-data' },
              { text: 'The panes', link: '/guide/panes' },
              { text: 'Volume layers', link: '/guide/volume-layers' },
              { text: 'Atlases & regions', link: '/guide/atlases-regions' },
              { text: 'Meshes', link: '/guide/meshes' },
              { text: 'Surfaces & annotations', link: '/guide/surfaces-annotations' },
              { text: 'Isosurfaces', link: '/guide/isosurfaces' },
              { text: 'Vector fields', link: '/guide/vector-fields' },
              { text: 'Points & electrodes', link: '/guide/points-electrodes' },
              { text: 'Measurements', link: '/guide/measurements' },
              { text: 'Coordinates', link: '/guide/coordinates' },
              { text: 'Themes & settings', link: '/guide/themes-settings' },
              { text: 'Scenes', link: '/guide/scenes' },
              { text: 'Screenshots & video', link: '/guide/screenshots-video' },
              { text: 'Keyboard shortcuts', link: '/guide/keyboard-shortcuts' },
              { text: 'Troubleshooting', link: '/guide/troubleshooting' },
            ],
          },
          { text: 'Automation & Python', link: '/automation' },
          { text: 'Gallery', link: '/gallery' },
          { text: 'Showcase', link: '/showcase' },
        ],
      },
      {
        text: 'Developers',
        collapsed: true,
        items: [
          { text: 'Building from source', link: '/developers/building' },
          { text: 'Architecture', link: '/developers/architecture' },
          { text: 'Decisions', link: '/developers/decisions' },
          { text: 'Testing', link: '/developers/testing' },
          { text: 'Benchmarks', link: '/developers/benchmarks' },
          { text: 'Roadmap', link: '/developers/roadmap' },
          { text: 'Releasing', link: '/developers/releasing' },
          { text: 'Contributing', link: '/developers/contributing' },
        ],
      },
    ],

    search: { provider: 'local' },

    docFooter: { prev: 'Previous', next: 'Next' },

    socialLinks: [{ icon: 'github', link: 'https://github.com/idossha/tetravox' }],

    footer: {
      message: 'MIT licensed. macOS and Linux first; a Windows build is published too.',
      copyright: 'Tetravox · a voxel + mesh viewer',
    },
  },
});
