import { defineConfig } from 'vitepress';

/**
 * The Tetravox documentation site.
 *
 * `base` is read from an env var so the same build serves both localhost
 * (`/`) and GitHub Pages under a project path (`/tetravox/`) — set
 * TETRAVOX_DOCS_BASE=/tetravox/ in the Pages workflow and leave it unset
 * locally.
 */
const base = process.env.TETRAVOX_DOCS_BASE ?? '/';

export default defineConfig({
  title: 'Tetravox',
  description:
    'A desktop viewer for voxel volumes (NIfTI) and finite-element / surface meshes, with a linked 3D view and orthogonal slices.',
  base,
  lang: 'en-US',
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: false,

  // website/src/ is generated by scripts/sync.mjs and scripts/gallery.mjs
  // (see those scripts) — it holds the pages pulled straight from docs/*.md.
  // `rewrites` drops the src/ segment from the URL so a generated page and a
  // hand-written one (index.md, get-started.md, showcase.md) sit at the same
  // URL depth — visitors never see the source/generated split.
  srcDir: '.',
  rewrites: {
    'src/viewing-data.md': 'viewing-data.md',
    'src/automation.md': 'automation.md',
    'src/gallery.md': 'gallery.md',
    'src/developers/architecture.md': 'developers/architecture.md',
    'src/developers/decisions.md': 'developers/decisions.md',
    'src/developers/testing.md': 'developers/testing.md',
    'src/developers/benchmarks.md': 'developers/benchmarks.md',
    'src/developers/roadmap.md': 'developers/roadmap.md',
    'src/developers/contributing.md': 'developers/contributing.md',
  },

  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}favicon.svg` }],
    ['meta', { name: 'theme-color', content: '#0f1720' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'Tetravox — voxel + mesh viewer' }],
    [
      'meta',
      {
        property: 'og:description',
        content:
          'A desktop viewer for voxel volumes and finite-element / surface meshes, one linked 3D view beside orthogonal slices.',
      },
    ],
  ],

  markdown: {
    theme: { light: 'github-light', dark: 'github-dark' },
    lineNumbers: false,
  },

  themeConfig: {
    siteTitle: 'Tetravox',
    outline: { level: [2, 3], label: 'On this page' },

    nav: [
      {
        text: 'Guide',
        link: '/',
        activeMatch: '^/(get-started|viewing-data|automation|gallery|showcase)',
      },
      {
        text: 'Developers',
        link: '/developers/architecture',
        activeMatch: '^/developers/',
      },
    ],

    sidebar: {
      '/developers/': [
        {
          text: 'Developers',
          collapsed: false,
          items: [
            { text: 'Architecture', link: '/developers/architecture' },
            { text: 'Decisions', link: '/developers/decisions' },
            { text: 'Testing', link: '/developers/testing' },
            { text: 'Benchmarks', link: '/developers/benchmarks' },
            { text: 'Roadmap', link: '/developers/roadmap' },
            { text: 'Contributing', link: '/developers/contributing' },
          ],
        },
      ],
      '/': [
        {
          text: 'Guide',
          collapsed: false,
          items: [
            { text: 'Home', link: '/' },
            { text: 'Get started', link: '/get-started' },
            { text: 'Viewing data', link: '/viewing-data' },
            { text: 'Automation & Python', link: '/automation' },
            { text: 'Gallery', link: '/gallery' },
            { text: 'Showcase', link: '/showcase' },
          ],
        },
      ],
    },

    search: { provider: 'local' },

    docFooter: { prev: 'Previous', next: 'Next' },

    socialLinks: [{ icon: 'github', link: 'https://github.com/idossha/tetravox' }],

    footer: {
      message: 'MIT licensed. macOS and Linux — no Windows build planned.',
      copyright: 'Tetravox · a voxel + mesh viewer',
    },
  },
});
