/**
 * §7.2's mesh passes — pass 1 (opaque) and pass 2 (transparent, two phases).
 *
 * The unit of work is a **sub-draw**: one tag range of one layer's surface (`SurfacePayload.perTag`)
 * with its own colour, its own opacity and its own world AABB. §7.2 says so in one line — "per-tag
 * sub-draws mean per-tag opacity sorts naturally" — and everything below follows from taking it
 * literally.
 *
 * The two-phase split, verbatim from §7.2:
 *
 * * **2a — back faces:** `cullFace(FRONT)`, depth test on, depth write off; objects sorted
 *   back-to-front by the depth of their **far** extent.
 * * **2b — front faces:** `cullFace(BACK)`, depth test on, depth write off; objects sorted
 *   back-to-front by the depth of their **near** extent.
 *
 * Unified rule: *in each phase, objects are sorted back-to-front by the depth of the sheet that phase
 * draws.* Exact for nested, individually near-convex shells (scalp, skull, CSF, blood — median 2
 * crossings `[M2Max]`); a partial improvement for GM/WM (median 4–6, p90 8–10).
 *
 * **`faceMode:'both'`, and the one place this file reads §7.2 rather than quoting it.** §7.2 excludes
 * those layers "from the split" and draws them "last in 2b". They *are* excluded from the scene-wide
 * sort and drawn after every split sub-draw — but each one is still issued as back faces **then**
 * front faces rather than as a single `CULL_FACE`-disabled draw. Every triangle is front- or
 * back-facing, so the two orderings rasterise **exactly the same fragments**; only the order differs,
 * and the two-draw order is the one §7.2's own unified rule implies. This is not a nicety:
 * `orient_surface` marks all ten of ernie's tissue tags open (§7.4's reference expectation), so §7.4
 * forces `faceMode:'both'` on every tissue layer, and a `cull none` draw would blend a shell's near
 * and far sheets in triangle-buffer order — the artefact §11's *Transparency (i)* names.
 *
 * Sorting needs a **per-tag** extent, not a per-layer one: every tag of a nested tissue complex
 * shares the dataset bbox to within its own thickness. `render/gpu.ts` measures a per-tag AABB once
 * at upload for that reason, and this file turns it into the near/far distances each phase sorts on.
 */

import { ProgramVariants } from '../../gl/program';
import type { Program, ShaderDefines } from '../../gl/program';
import { GL_STATE } from '../../gl/state';
import type { GlState } from '../../gl/state';
import { VertexArray } from '../../gl/buffer';
import { collectDrawItems } from './pass';
import type { FramePass, PassContext } from './pass';
import { MESH_COLOR_SOURCE, MESH_FS, MESH_THRESHOLD, MESH_VS } from '../../shaders';
import { MAX_CLIP_PLANES } from '../../gl/state';
import type { MeshDrawItem, MeshDrawStyle } from '../../layers/runtime';
import type { CapGeometry, GpuStore, SurfaceGeometry } from '../gpu';
import { isSliceView } from '../../scene/store';
import type { Aabb, mat4, MeshDataset, MeshLayer, Plane, vec3, vec4 } from '../../scene/types';

/** Texture units, fixed so a variant switch never has to re-bind. */
const UNIT = { lut: 0, field: 1, owner: 2, palette: 3, edgeMask: 4 } as const;

/** The largest finite f32, for a threshold bound the scene left at ±Infinity. */
const F32_MAX = 3.4e38;

/** `uClipSkip`'s "no plane is exempt" value — every draw that is not a cap. */
const NO_CLIP_SKIP = -1;

/** The shared empty plane list, so an unclipped layer costs no allocation per draw (§7.1). */
const NO_PLANES: readonly Plane[] = Object.freeze([]);

/** One tag range of one layer: the thing §7.2 sorts and blends. */
export interface SubDraw {
  item: MeshDrawItem;
  tag: number;
  first: number;
  count: number;
  color: vec4;
  /** `tagStyle[tag].opacity * layer.opacity`. */
  alpha: number;
  bounds: Aabb;
  /** R5: this tag is selected, so it is drawn with edge emphasis. */
  emphasised: boolean;
}

/**
 * One plane's cap, from `compute/cut-manager.ts` — the unit §7.4's **cap rule** applies to.
 *
 * There is one of these per *plane*, never one per layer, because the rule is per plane: "when
 * drawing the cap generated by plane *i*, disable `CLIP_DISTANCE(i)` for that draw while leaving the
 * others enabled".
 */
export interface CapDraw {
  item: MeshDrawItem;
  geom: CapGeometry;
  /** Index into the layer's **active** clip planes — the one this draw is exempt from. */
  plane: number;
  /** The (negated) plane normal §7.4 makes the cap's normal, in world space. */
  normal: vec3;
  first: number;
  count: number;
  /** §7.2: "Cut caps are drawn … with that layer's opacity." */
  alpha: number;
  /** Distance from the eye to the plane's foot point under the layer's bbox centre (§7.2's sort). */
  depth: number;
}

/** The compile-time key of one sub-draw's program (`shaders/mesh.ts`'s defines). */
export interface MeshVariant {
  TVX_COLOR_SOURCE: 0 | 1 | 2 | 3 | 4;
  TVX_EDGES: 0 | 1;
  TVX_EDGE_MASK: 0 | 1;
  TVX_FLAT_SHADING: 0 | 1;
  TVX_THRESHOLD: 0 | 1 | 2;
  TVX_EMPHASIS: 0 | 1;
  /** §7.4: N ∈ 0..6. The variant key, because a clip distance costs a whole varying vector (§7.1). */
  TVX_CLIP_PLANES: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  /** 1 selects the `vec4`-uniform + `discard` fallback; both paths must be pixel-identical (§11). */
  TVX_CLIP_DISCARD: 0 | 1;
  /** 1 selects the cap attribute set and the uniform cap normal. */
  TVX_CAP: 0 | 1;
}

/**
 * §7.4's "up to 6 world-space planes", as the pass sees them: the layer's **enabled** planes, in
 * order, capped at six.
 *
 * The cap rule indexes this list, and so does `GlState.clipDistances`, so "plane *i*" means the same
 * thing in the shader, in the GL enable set and in the cut's `planeRanges` — which is only true
 * because the cut was requested with exactly this list (`layers/mesh.ts`).
 */
export function activeClipPlanes(layer: MeshLayer): readonly Plane[] {
  // The overwhelmingly common case is "no clip planes at all", and §7.1 asks for no per-frame
  // allocations — so it returns the one frozen empty array rather than a fresh one per draw.
  if (layer.clip.planes.length === 0) return NO_PLANES;
  const out: Plane[] = [];
  for (const cp of layer.clip.planes) {
    if (!cp.enabled) continue;
    out.push(cp.plane);
    if (out.length === MAX_CLIP_PLANES) break;
  }
  return out.length === 0 ? NO_PLANES : out;
}

/** `uClipPlanes` as the shader wants it: `.xyz` = normal, `.w` = offset, N planes packed flat. */
export function packClipPlanes(planes: readonly Plane[]): Float32Array {
  const out = new Float32Array(planes.length * 4);
  planes.forEach((p, i) => {
    out[i * 4] = p.normal[0];
    out[i * 4 + 1] = p.normal[1];
    out[i * 4 + 2] = p.normal[2];
    out[i * 4 + 3] = p.offset;
  });
  return out;
}

/**
 * §7.2's sort key for a translucent cap: "sorted by the clip plane's depth at the object centre".
 *
 * The foot of the perpendicular from the bbox centre onto the plane is the point of the cap nearest
 * to what the layer occupies, so its distance from the eye orders two caps of one object the way the
 * sheets they stand in for would sort.
 */
export function capDepth(plane: Plane, bounds: Aabb, eye: vec3): number {
  const c: vec3 = [
    (bounds.min[0] + bounds.max[0]) / 2,
    (bounds.min[1] + bounds.max[1]) / 2,
    (bounds.min[2] + bounds.max[2]) / 2,
  ];
  const d = plane.normal[0] * c[0] + plane.normal[1] * c[1] + plane.normal[2] * c[2] + plane.offset;
  return Math.hypot(
    c[0] - plane.normal[0] * d - eye[0],
    c[1] - plane.normal[1] * d - eye[1],
    c[2] - plane.normal[2] * d - eye[2]
  );
}

/**
 * Every cap draw one layer contributes, one per plane that produced geometry.
 *
 * A plane with no cut triangles contributes nothing — a plane entirely outside the mesh cuts nothing,
 * and drawing a zero-length range would still cost a program switch and a clip-state change.
 */
export function capDraws(item: MeshDrawItem, eye: vec3): CapDraw[] {
  const geom = item.caps;
  if (geom === undefined || !item.layer.clip.caps) return [];
  const planes = activeClipPlanes(item.layer);
  const out: CapDraw[] = [];
  for (const range of geom.planeRanges) {
    const plane = planes[range.plane];
    if (plane === undefined || range.vertexCount === 0) continue;
    out.push({
      item,
      geom,
      plane: range.plane,
      // §7.4: "Cap normals are the (negated) clip-plane normal." The kept half-space is
      // `dot(n, x) + d >= 0`, so the cap's outward direction — the one facing the removed half — is
      // `-n`, and a headlight then lights the cap the viewer is looking into.
      normal: [-plane.normal[0], -plane.normal[1], -plane.normal[2]],
      first: range.firstVertex,
      count: range.vertexCount,
      alpha: item.layer.opacity,
      depth: capDepth(plane, item.ds.bounds, eye),
    });
  }
  return out;
}

/** Distance from `eye` to the farthest corner of `b` — the depth phase 2a sorts on. */
export function farExtent(b: Aabb, eye: vec3): number {
  let worst = 0;
  for (let c = 0; c < 8; c += 1) {
    const x = ((c & 1) === 0 ? b.min[0] : b.max[0]) - eye[0];
    const y = ((c & 2) === 0 ? b.min[1] : b.max[1]) - eye[1];
    const z = ((c & 4) === 0 ? b.min[2] : b.max[2]) - eye[2];
    const d = x * x + y * y + z * z;
    if (d > worst) worst = d;
  }
  return Math.sqrt(worst);
}

/** Distance from `eye` to the nearest point of `b` (0 inside it) — the depth phase 2b sorts on. */
export function nearExtent(b: Aabb, eye: vec3): number {
  let sum = 0;
  for (let c = 0; c < 3; c += 1) {
    const lo = b.min[c] ?? 0;
    const hi = b.max[c] ?? 0;
    const e = eye[c] ?? 0;
    const d = e < lo ? lo - e : e > hi ? e - hi : 0;
    sum += d * d;
  }
  return Math.sqrt(sum);
}

/**
 * §7.4's `faceMode`: `'both'` is **forced** when the surface has open components, which every tagged
 * tissue complex has — an interface triangle's winding is arbitrary.
 */
export function culls(layer: MeshLayer, ds: MeshDataset): boolean {
  return layer.faceMode === 'cull' && ds.orient.openComponents === 0;
}

/**
 * The colour of one tag: the layer's per-tag override, then the dataset's own tag colour (from
 * `$PhysicalNames` / `.msh.opt` / the §7.6 default palette), then the layer's solid colour.
 *
 * §4.1 requires the dataset's 0..255 wire value to round-trip **exactly** through the engine's 0..1
 * representation, which §11's "the cap pixel is the tag colour" test pins.
 */
export function tagColor(layer: MeshLayer, ds: MeshDataset, tag: number): vec4 {
  if (layer.colorMode === 'solid') return layer.solidColor;
  const style = layer.tagStyle[tag];
  if (style?.color !== undefined) return style.color;
  const t = ds.tags.find((x) => x.id === tag);
  return t?.color ?? layer.solidColor;
}

/**
 * §4.2's threshold, reduced to the shader's `TVX_THRESHOLD`.
 *
 * `mode:'clamp'` needs no shader branch — the CPU bake already clamps the ends of the colormap — and
 * a threshold that hides nothing compiles away entirely, which keeps the default variant identical
 * to Phase 1's.
 */
export function thresholdVariant(layer: MeshLayer, colorSource: number): 0 | 1 | 2 {
  if (colorSource !== MESH_COLOR_SOURCE.nodeField && colorSource !== MESH_COLOR_SOURCE.elmField) {
    return MESH_THRESHOLD.none;
  }
  const t = layer.threshold;
  if (t.mode !== 'hide') return MESH_THRESHOLD.none;
  if (!Number.isFinite(t.lo) && !Number.isFinite(t.hi)) return MESH_THRESHOLD.none;
  return t.symmetric ? MESH_THRESHOLD.hideSymmetric : MESH_THRESHOLD.hide;
}

/**
 * The colour source a sub-draw can actually use, given what has landed on the GPU.
 *
 * §7.4 calls the de-indexed variant, the element field and `colorMode:'label'` "async loads with a
 * progress state, not instant checkboxes". Until one lands, the geometry or the table is simply
 * absent, and the honest thing to draw is the tag colour — never a half-applied field.
 */
export function effectiveColorSource(
  style: MeshDrawStyle | undefined,
  geom: SurfaceGeometry
): 0 | 1 | 2 | 3 {
  if (style === undefined) return MESH_COLOR_SOURCE.uniform;
  switch (style.colorSource) {
    case MESH_COLOR_SOURCE.nodeField:
      return style.fieldTable !== undefined && geom.hasNodeIndex
        ? MESH_COLOR_SOURCE.nodeField
        : MESH_COLOR_SOURCE.uniform;
    case MESH_COLOR_SOURCE.elmField:
      return style.fieldTable !== undefined && geom.ownerTexture !== null
        ? MESH_COLOR_SOURCE.elmField
        : MESH_COLOR_SOURCE.uniform;
    case MESH_COLOR_SOURCE.label:
      return style.fieldTable !== undefined && style.palette !== undefined && geom.hasNodeIndex
        ? MESH_COLOR_SOURCE.label
        : MESH_COLOR_SOURCE.uniform;
    default:
      return MESH_COLOR_SOURCE.uniform;
  }
}

/**
 * Which clip path this frame compiles: the number of active planes, and whether it is the hardware
 * or the `discard` one.
 *
 * `forceDiscardClip` and an absent `WEBGL_clip_cull_distance` produce the *same* program — which is
 * exactly what §11's clip-path equivalence test needs, since one of them is reachable on every
 * machine and the other is not.
 */
export function clipVariant(
  layer: MeshLayer,
  input: { clipDistance?: boolean; forceDiscardClip?: boolean }
): { TVX_CLIP_PLANES: MeshVariant['TVX_CLIP_PLANES']; TVX_CLIP_DISCARD: 0 | 1 } {
  const n = activeClipPlanes(layer).length as MeshVariant['TVX_CLIP_PLANES'];
  const hardware = input.clipDistance === true && input.forceDiscardClip !== true;
  return { TVX_CLIP_PLANES: n, TVX_CLIP_DISCARD: n > 0 && !hardware ? 1 : 0 };
}

/** The §7.1 variant one sub-draw compiles to. */
export function variantOf(
  d: SubDraw,
  input: { clipDistance?: boolean; forceDiscardClip?: boolean; edges?: boolean } = {}
): MeshVariant {
  const { layer, geom, style } = d.item;
  const colorSource = effectiveColorSource(style, geom);
  // Edges need the de-indexed variant's `corner` attribute — §7.4's masked barycentric mechanism is
  // the only one, for surfaces and caps alike, so an indexed draw simply has no edges yet.
  // `input.edges === false` is §7.2's `interacting` level; emphasis is not gated (see qualityEdges).
  const surfaceEdges = layer.edges.surface && input.edges !== false;
  const wantEdges = (surfaceEdges || d.emphasised) && geom.hasCorner;
  return {
    TVX_COLOR_SOURCE: colorSource,
    TVX_EDGES: wantEdges ? 1 : 0,
    TVX_EDGE_MASK: wantEdges && geom.edgeMaskTexture !== null ? 1 : 0,
    TVX_FLAT_SHADING: layer.flatShading ? 1 : 0,
    TVX_THRESHOLD: thresholdVariant(layer, colorSource),
    TVX_EMPHASIS: colorSource === MESH_COLOR_SOURCE.label && style?.labelEmphasis === true ? 1 : 0,
    ...clipVariant(layer, input),
    TVX_CAP: 0,
  };
}

/**
 * The colour source a **cap** can actually use, given what has landed.
 *
 * `capColorMode:'tag'` is the per-element tet tag; `'inherit'` follows the layer's own `colorMode`
 * as far as a cut vertex can. The one mode that cannot follow is `'label'`: a `.annot` /
 * `.label.gii` id is a **node** quantity and a cut vertex sits *between* two nodes, where the id is
 * undefined — so it falls back to the tag, which is what a cross-section through tissue means
 * anyway.
 */
export function effectiveCapColorSource(item: MeshDrawItem): 0 | 1 | 2 | 4 {
  const style = item.style;
  const wanted = style?.capColorSource ?? MESH_COLOR_SOURCE.capTag;
  if (wanted === MESH_COLOR_SOURCE.capTag) {
    return style?.capPalette !== undefined ? MESH_COLOR_SOURCE.capTag : MESH_COLOR_SOURCE.uniform;
  }
  if (wanted === MESH_COLOR_SOURCE.nodeField || wanted === MESH_COLOR_SOURCE.elmField) {
    return style?.fieldTable !== undefined ? wanted : MESH_COLOR_SOURCE.uniform;
  }
  return MESH_COLOR_SOURCE.uniform;
}

/** The §7.1 variant one cap draw compiles to. */
export function capVariantOf(
  c: CapDraw,
  input: { clipDistance?: boolean; forceDiscardClip?: boolean; edges?: boolean } = {}
): MeshVariant {
  const layer = c.item.layer;
  const colorSource = effectiveCapColorSource(c.item);
  // §7.4: "Cap edges use the same shader", and `Cut.edge_mask` always exists — a 1-3 split is 0b111,
  // a 2-2 split is 0b101 / 0b011, which is what suppresses the quad diagonal.
  const wantEdges = layer.edges.caps && input.edges !== false;
  return {
    TVX_COLOR_SOURCE: colorSource,
    TVX_EDGES: wantEdges ? 1 : 0,
    TVX_EDGE_MASK: wantEdges ? 1 : 0,
    // A cap is planar and its normal is a uniform, so a face normal from derivatives would be the
    // same vector at a higher price. Flat shading is a property of the *surface* draw.
    TVX_FLAT_SHADING: 0,
    TVX_THRESHOLD: thresholdVariant(layer, colorSource),
    TVX_EMPHASIS: 0,
    ...clipVariant(layer, input),
    TVX_CAP: 1,
  };
}

/** Every sub-draw one layer contributes, in `perTag` order. */
export function subDraws(item: MeshDrawItem): SubDraw[] {
  const { layer, ds, geom } = item;
  const emphasis = new Set(item.style?.emphasisTags ?? []);
  const out: SubDraw[] = [];
  for (const range of geom.perTag) {
    const style = layer.tagStyle[range.tag];
    if (style !== undefined && !style.visible) continue;
    const alpha = (style?.opacity ?? 1) * layer.opacity;
    if (alpha <= 0) continue;
    out.push({
      item,
      tag: range.tag,
      first: range.first,
      count: range.count,
      color: tagColor(layer, ds, range.tag),
      alpha,
      bounds: geom.tagBounds?.get(range.tag) ?? ds.bounds,
      emphasised: emphasis.has(range.tag),
    });
  }
  return out;
}

interface FrameUniforms {
  viewProj: mat4;
  eye: vec3;
  ambient: number;
  store: GpuStore;
  /** `caps.clipDistance` after `forceCaps` (§7.1). */
  clipDistance: boolean;
  /** §11's clip-path axis (`EngineOptions.forceDiscardClip`). */
  forceDiscardClip: boolean;
  /** `Scene.quality.edges` — §7.2's `interacting` fallback set. See {@link qualityEdges}. */
  edges: boolean;
}

/**
 * §7.2's `edges` knob, read off the scene's current `QualityLevel`.
 *
 * §7.2: "While interacting, the `interacting` `QualityLevel` applies: `dprScale 1`, `msaa 0`,
 * **`edges false`**, `capDecimation` per §9." This is the one place the flag is consumed, and it is
 * consumed here because a barycentric edge is a *shader variant* (`TVX_EDGES`), so switching it off
 * costs a program bind rather than a re-upload — nothing about the geometry, the cut or the field
 * tables changes, which is what makes it safe to flip inside a drag.
 *
 * **Label emphasis is deliberately not gated.** `TVX_EMPHASIS` draws R5's selected-region outline,
 * and §7.2's own rule for the fallback set is "any knob that changes displayed *values* rather than
 * displayed *resolution*" is forbidden. Which region is selected is a value the user is reading, in
 * exactly the sense `interpolation` is; dropping it mid-drag would make a selection blink out while
 * the user drags to inspect it. `edges.surface` / `edges.caps` are wireframe, which is resolution.
 *
 * A missing `quality` (a hand-built `DrawInput` in a unit test, or the no-GL engine) means full.
 */
export function qualityEdges(input: { scene?: { quality?: { edges?: boolean } } }): boolean {
  return input.scene?.quality?.edges !== false;
}

export class MeshPass implements FramePass {
  readonly name = 'mesh' as const;

  readonly #gl: WebGL2RenderingContext;
  readonly #state: GlState;
  /** §7.1's variant cache. One program per distinct set of `shaders/mesh.ts` defines. */
  readonly #programs: ProgramVariants;
  #frame: FrameUniforms | null = null;
  #bound: Program | null = null;
  /** The clip state currently programmed, so a run of same-layer draws issues nothing per draw. */
  #clip: string | null = null;
  /** §7.1's "no per-frame allocations": the `uClipPlanes` payload, filled in place. */
  readonly #clipScratch = new Float32Array(MAX_CLIP_PLANES * 4);
  /** One layer's active planes, resolved once per frame rather than once per sub-draw. */
  readonly #planes = new Map<string, readonly Plane[]>();

  constructor(gl: WebGL2RenderingContext, state: GlState) {
    this.#gl = gl;
    this.#state = state;
    this.#programs = new ProgramVariants(gl, MESH_VS, MESH_FS);
  }

  run(ctx: PassContext): void {
    const { view, eye, viewProj, input } = ctx;
    // Meshes draw in 3D panes here; §7.4's 2D `contoursIn2D` / `fillIn2D` are E-DERIVED's items. The
    // runtimes already return nothing for a 2D pane, and this guard keeps the GL state changes below
    // off the 2D path entirely.
    if (isSliceView(view)) return;
    const items = collectDrawItems(input, view).filter((d): d is MeshDrawItem => d.kind === 'mesh');
    if (items.length === 0) return;

    const state = this.#state;
    this.#frame = {
      viewProj,
      eye,
      ambient: input.scene.lighting.ambient,
      store: input.store,
      clipDistance: input.clipDistance === true,
      forceDiscardClip: input.forceDiscardClip === true,
      edges: qualityEdges(input),
    };
    this.#bound = null;
    this.#clip = null;
    this.#planes.clear();
    for (const item of items) this.#planes.set(item.layer.id, activeClipPlanes(item.layer));

    const all = items.flatMap((item) => subDraws(item));
    const opaque = all.filter((d) => d.alpha >= 1);
    const translucent = all.filter((d) => d.alpha < 1);
    // §7.2 pass 1 lists "the cut caps of opaque layers"; a translucent layer's caps go in pass 2
    // "in the same pass as their owning layer, with that layer's opacity".
    const caps = items.flatMap((item) => capDraws(item, eye));
    const capsOpaque = caps.filter((c) => c.alpha >= 1);
    const capsTranslucent = caps.filter((c) => c.alpha < 1 && c.alpha > 0);

    // Pass 1 — opaque.
    state.apply(GL_STATE.opaque3d);
    for (const d of opaque) {
      state.cull(culls(d.item.layer, d.item.ds) ? 'back' : 'none');
      this.#draw(d);
    }
    for (const c of capsOpaque) {
      // A cap is one sheet: `plane_cut`'s polygon winding is not oriented, so culling either face
      // would delete half of it.
      state.cull('none');
      this.#drawCap(c);
    }

    // Pass 2 — transparent, two phases (§7.2). Back-to-front is descending distance, and each phase
    // uses the extent of the sheet it draws.
    if (translucent.length > 0) {
      const split = translucent.filter((d) => culls(d.item.layer, d.item.ds));
      const both = translucent.filter((d) => !culls(d.item.layer, d.item.ds));
      const byFar = (xs: SubDraw[]): SubDraw[] =>
        [...xs].sort((a, b) => farExtent(b.bounds, eye) - farExtent(a.bounds, eye));
      const byNear = (xs: SubDraw[]): SubDraw[] =>
        [...xs].sort((a, b) => nearExtent(b.bounds, eye) - nearExtent(a.bounds, eye));

      state.apply(GL_STATE.transparentBack); // 2a — back faces
      for (const d of byFar(split)) this.#draw(d);
      state.apply(GL_STATE.transparentFront); // 2b — front faces
      for (const d of byNear(split)) this.#draw(d);

      // Excluded from the scene-wide split and drawn last in 2b (§7.2) — but still back sheet before
      // front sheet, which rasterises the same fragments as a `CULL_FACE`-disabled draw in the order
      // §7.2's own rule implies. See this file's header.
      if (both.length > 0) {
        state.apply(GL_STATE.transparentBack);
        for (const d of byFar(both)) this.#draw(d);
        state.apply(GL_STATE.transparentFront);
        for (const d of byNear(both)) this.#draw(d);
      }
    }
    if (capsTranslucent.length > 0) {
      // §7.2: "in the transparent pass a cap is a single sheet — `CULL_FACE` disabled, sorted by the
      // clip plane's depth at the object centre." Last in 2b, after every sheet it stands in front
      // of, because everything on its own side of the plane has been clipped away.
      state.apply(GL_STATE.transparentFront);
      state.cull('none');
      for (const c of [...capsTranslucent].sort((a, b) => b.depth - a.depth)) this.#drawCap(c);
    }
    // Depth writes back on before the pass returns: `render/renderer.ts` clears the next pane's depth
    // buffer, and `gl.clear(DEPTH_BUFFER_BIT)` is masked by `depthMask`.
    state.apply(GL_STATE.opaque3d);
    // **And the clip set goes back to empty.** The enable set is global and survives `useProgram`
    // `[M2Max]`, so leaving it on would clip the *next pane's* slice quad — which draws in pass 1,
    // before any mesh pass runs again. §7.4: "Reset per pass."
    state.clipDistances(0);
    this.#frame = null;
    this.#bound = null;
    this.#clip = null;
  }

  /**
   * §7.4's clip state for one draw: the layer's active planes, minus `skip` (the plane whose own cap
   * this is, or −1).
   *
   * Both paths are programmed from here so the cap rule is written once. The hardware path moves the
   * `CLIP_DISTANCE` enable set; the fallback moves a uniform. Nothing else in the file decides it.
   */
  #applyClip(item: MeshDrawItem, prog: Program, skip: number): void {
    const frame = this.#frame;
    if (frame === null) return;
    const planes = this.#planes.get(item.layer.id) ?? [];
    const hardware = frame.clipDistance && !frame.forceDiscardClip;
    if (planes.length > 0) {
      const scratch = this.#clipScratch;
      planes.forEach((p, i) => {
        scratch[i * 4] = p.normal[0];
        scratch[i * 4 + 1] = p.normal[1];
        scratch[i * 4 + 2] = p.normal[2];
        scratch[i * 4 + 3] = p.offset;
      });
      // Uniforms are per program, so they are re-sent on every draw rather than cached: a variant
      // switch between two draws of the same layer would otherwise leave the new program's planes
      // at zero and clip nothing.
      prog.vec4('uClipPlanes', scratch.subarray(0, planes.length * 4));
      if (!hardware) prog.int('uClipSkip', skip);
    }
    const key = `${item.layer.id}|${String(skip)}`;
    if (this.#clip === key) return;
    this.#clip = key;
    // Gated on the capability: `gl.enable(CLIP_DISTANCE0_WEBGL + i)` without
    // `WEBGL_clip_cull_distance` is an `INVALID_ENUM`, and `GlState` issues no call while the set is
    // already empty — which is what keeps the fallback path from touching it at all.
    this.#state.clipDistances(hardware ? planes.length : 0, hardware ? skip : undefined);
  }

  /**
   * One sub-draw: one tag range, with the tag colour as a **uniform** on §7.4's indexed variant.
   *
   * `tagStyle[tag].visible` is a skipped sub-draw, which is free; there is deliberately no per-vertex
   * `tag` attribute, because 1,048,599 of ernie's 1,177,213 interface faces are shared between two
   * tissue tags `[DATA]` and a per-vertex tag is ill-defined on a shared node.
   */
  #draw(d: SubDraw): void {
    const gl = this.#gl;
    const frame = this.#frame;
    if (frame === null) return;
    const { layer, ds, geom, style } = d.item;
    const variant = variantOf(d, frame);
    const prog = this.#programs.get(variant as unknown as ShaderDefines);

    if (prog !== this.#bound) {
      prog.use();
      prog.mat4('uViewProj', frame.viewProj);
      prog.vec3('uEye', frame.eye);
      prog.float('uAmbient', frame.ambient);
      this.#bound = prog;
    }

    const source = variant.TVX_COLOR_SOURCE;
    if (source === MESH_COLOR_SOURCE.nodeField || source === MESH_COLOR_SOURCE.elmField) {
      // §7.6's baked LUT: `kind:'heat'` "costs nothing extra in the shader — it is a different bake".
      const lut = frame.store.lut(layer.scale, layer.colormap, layer.colormapNegative);
      gl.activeTexture(gl.TEXTURE0 + UNIT.lut);
      gl.bindTexture(gl.TEXTURE_2D, lut.texture);
      prog.int('uLut', UNIT.lut);
      prog.float('uLutLo', lut.lo);
      prog.float('uLutHi', lut.hi === lut.lo ? lut.lo + 1 : lut.hi);
      const table = style?.fieldTable;
      if (table !== undefined) {
        gl.activeTexture(gl.TEXTURE0 + UNIT.field);
        gl.bindTexture(gl.TEXTURE_2D, table.texture);
        prog.int('uFieldTex', UNIT.field);
        prog.int('uFieldWidth', table.width);
      }
      if (source === MESH_COLOR_SOURCE.elmField && geom.ownerTexture !== null) {
        gl.activeTexture(gl.TEXTURE0 + UNIT.owner);
        gl.bindTexture(gl.TEXTURE_2D, geom.ownerTexture);
        prog.int('uOwnerTex', UNIT.owner);
        prog.int('uOwnerWidth', geom.ownerWidth);
      }
      if (variant.TVX_THRESHOLD !== MESH_THRESHOLD.none) {
        const t = layer.threshold;
        const lo = Number.isFinite(t.lo) ? t.lo : -F32_MAX;
        const hi = Number.isFinite(t.hi) ? t.hi : F32_MAX;
        const span = Math.abs(hi - lo);
        prog.float('uThreshLo', lo);
        prog.float('uThreshHi', hi);
        // §4.2: the ramp width is `softEdge` as a fraction of `hi - lo`. Floored just above zero, so
        // the shader's `smoothstep` never sees two equal edges — which GLSL leaves undefined.
        prog.float('uThreshSoft', Math.max(t.softEdge * span, span * 1e-6, 1e-30));
      }
    } else if (source === MESH_COLOR_SOURCE.label) {
      const table = style?.fieldTable;
      const palette = style?.palette;
      if (table !== undefined) {
        gl.activeTexture(gl.TEXTURE0 + UNIT.field);
        gl.bindTexture(gl.TEXTURE_2D, table.texture);
        prog.int('uFieldTex', UNIT.field);
        prog.int('uFieldWidth', table.width);
      }
      if (palette !== undefined) {
        gl.activeTexture(gl.TEXTURE0 + UNIT.palette);
        gl.bindTexture(gl.TEXTURE_2D, palette.texture);
        prog.int('uPalette', UNIT.palette);
        prog.int('uPaletteSize', palette.size);
      }
    }

    if (variant.TVX_EDGES === 1 || variant.TVX_EMPHASIS === 1) {
      prog.vec4('uEdgeColor', layer.edgeColor);
      prog.float('uEdgeWidthPx', Math.max(0.5, layer.edgeWidthPx));
    }
    if (variant.TVX_EDGE_MASK === 1 && geom.edgeMaskTexture !== null) {
      gl.activeTexture(gl.TEXTURE0 + UNIT.edgeMask);
      gl.bindTexture(gl.TEXTURE_2D, geom.edgeMaskTexture);
      prog.int('uEdgeMaskTex', UNIT.edgeMask);
      prog.int('uEdgeMaskWidth', geom.edgeMaskWidth);
    }

    // Every plane clips a surface draw — `NO_CLIP_SKIP`, because a surface is nobody's cap.
    this.#applyClip(d.item, prog, NO_CLIP_SKIP);
    prog.mat4('uModel', ds.transform);
    prog.vec4('uColor', d.color);
    prog.float('uOpacity', d.alpha);
    geom.vao.bind();
    if (geom.indexed) {
      gl.drawElements(gl.TRIANGLES, d.count, gl.UNSIGNED_INT, d.first * 4);
    } else {
      gl.drawArrays(gl.TRIANGLES, d.first, d.count);
    }
    VertexArray.unbind(gl);
  }

  /**
   * One plane's cap: `plane_cut`'s exact polygons, in the layer's own material, under §7.4's cap rule.
   *
   * The rule is the whole reason this is a separate draw: **plane `c.plane` must not clip it.** Cap
   * vertices lie exactly *on* that plane, and CPU f32 interpolation against a vertex-shader
   * recomputation straddles zero per vertex — `gl_ClipDistance == 0.0` keeps the primitive and
   * `−1e-7` deletes it entirely `[M2Max]` — so a cap drawn under its own plane's clip vanishes in
   * patches. Every *other* plane still clips it, which is what makes two planes cut a corner rather
   * than two overlapping sheets.
   */
  #drawCap(c: CapDraw): void {
    const gl = this.#gl;
    const frame = this.#frame;
    if (frame === null || c.count === 0) return;
    const { layer, ds, style } = c.item;
    const variant = capVariantOf(c, frame);
    const prog = this.#programs.get(variant as unknown as ShaderDefines);

    if (prog !== this.#bound) {
      prog.use();
      prog.mat4('uViewProj', frame.viewProj);
      prog.vec3('uEye', frame.eye);
      prog.float('uAmbient', frame.ambient);
      this.#bound = prog;
    }

    const source = variant.TVX_COLOR_SOURCE;
    if (source === MESH_COLOR_SOURCE.nodeField || source === MESH_COLOR_SOURCE.elmField) {
      const lut = frame.store.lut(layer.scale, layer.colormap, layer.colormapNegative);
      gl.activeTexture(gl.TEXTURE0 + UNIT.lut);
      gl.bindTexture(gl.TEXTURE_2D, lut.texture);
      prog.int('uLut', UNIT.lut);
      prog.float('uLutLo', lut.lo);
      prog.float('uLutHi', lut.hi === lut.lo ? lut.lo + 1 : lut.hi);
      const table = style?.fieldTable;
      if (table !== undefined) {
        gl.activeTexture(gl.TEXTURE0 + UNIT.field);
        gl.bindTexture(gl.TEXTURE_2D, table.texture);
        prog.int('uFieldTex', UNIT.field);
        prog.int('uFieldWidth', table.width);
      }
      if (variant.TVX_THRESHOLD !== MESH_THRESHOLD.none) {
        const t = layer.threshold;
        const lo = Number.isFinite(t.lo) ? t.lo : -F32_MAX;
        const hi = Number.isFinite(t.hi) ? t.hi : F32_MAX;
        const span = Math.abs(hi - lo);
        prog.float('uThreshLo', lo);
        prog.float('uThreshHi', hi);
        prog.float('uThreshSoft', Math.max(t.softEdge * span, span * 1e-6, 1e-30));
      }
    } else if (source === MESH_COLOR_SOURCE.capTag) {
      const palette = style?.capPalette;
      if (palette !== undefined) {
        gl.activeTexture(gl.TEXTURE0 + UNIT.palette);
        gl.bindTexture(gl.TEXTURE_2D, palette.texture);
        prog.int('uPalette', UNIT.palette);
        prog.int('uPaletteSize', palette.size);
      }
    }

    if (variant.TVX_EDGES === 1) {
      prog.vec4('uEdgeColor', layer.edgeColor);
      prog.float('uEdgeWidthPx', Math.max(0.5, layer.edgeWidthPx));
    }

    this.#applyClip(c.item, prog, c.plane);
    prog.vec3('uCapNormal', c.normal);
    prog.mat4('uModel', ds.transform);
    prog.vec4('uColor', layer.solidColor);
    prog.float('uOpacity', c.alpha);
    c.geom.vao.bind();
    gl.drawArrays(gl.TRIANGLES, c.first, c.count);
    VertexArray.unbind(gl);
  }

  dispose(): void {
    this.#programs.dispose();
  }
}
